# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
commands: 
  destroy_env:
    steps:
     - run:
         name: Destroy Env
         when: on_fail
         command: aws cloudformation delete-stack  --stack-name mystack-${CIRCLE_WORKFLOW_ID}
jobs:
  create-infra:
    docker:
      - image: amazon/aws-cli  
    steps:
      - checkout
      - run:
         name: "run Cloud Formation stack"
         command: aws cloudformation create-stack  --stack-name mystack-${CIRCLE_WORKFLOW_ID} --region us-east-1 --template-body file://cftemplate.yml
  configure-infra-with-ansible:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: python:3.7-alpine3.11  
    steps:
      - checkout
      - add_ssh_keys: 
          fingerprints: ["3f:04:ee:cd:d9:c7:f5:18:90:65:2f:b7:9b:a6:56:54"]
      - run:
          name: "Install ansible"
          command: apk add --update ansible
      - run:
          name: "run ansible playbook"
          command: ansible-playbook main-remote.yml -i inventory    
 
  run-smoke-test: 
    docker:
      - image: alpine:latest  
    steps:
      - run: apk add --update curl
      - run:
          name: "smoke test"
          command:  |
           URL="http://3.236.128.118:3000"
           if curl -s --head ${URL}
           then 
             return 0
           else
             return 1
           fi  

  run-smoke-test-V1: 
    docker:
      - image: alpine:latest  
    steps:
      - run:
          name: "Test job"
          command:  return 1
      - destroy_env    




workflows:
  circle-ansible-workflow:
    jobs:
      - create-infra
      - run-smoke-test-V1:
            requires:
             - create-infra
