- name: "update apt pkg"
  become: yes
  apt:
    update_cache: yes
- name: "upgrade apt pkg"
  become: yes
  apt:
    upgrade: yes
- name: "remove dependencies that are not reqd"
  become: yes
  apt:
    autoremove: yes
- name: "install node dependencies"
  become: yes
  apt:
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create directory"
  file:
    path: ~/web
    state: directory
- name: "copy index.js"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"
- name: "start and execute node"
  shell: pm2 start ~/web/index.js -f                              
